const Affirmative = {
    name: "Affirmative",
    utterances: [
        "Yes",
        "Yeah",
        "Yep",
        "Yup",
        "Yah",
        "Sure",
        "It is",
        "Totally",
        "It did",
        "Yea",
        "Yes it is",
        "Yes please",
        "Ok",
        "O.k.",
        "No problem",
        "Fine",
        "K",
        "Okay",
        "Okie doke",
        "Yes there is",
        "Yes it is",
        "I am not sure",
        "I'm not sure",
        "maybe",
        "I think so",
        "I think",
        "There is a public safety concern",
        "This is a safetly concern",
        "This is an immediate public safety concern",
        "This is an immediate safety concern",
        "There is a concern for public safety",
        "There is an immediate concern for public safety",
        "This does involve public safety",
        "This does involve immediate public safety",
        "This invovles public safety",
        "This involves immediate public safety",
        "This is about public safety",
        "This is about immediate public safety",
        "This does concern public safety",
        "This does concern immediate public safety",
        "This is a public safety concern",
        "Yes I am reporting a public safety concern",
        "Yes this affects public safety",
        "Yes this invovles public safety",
        "Yes this concerns public safety",
        "Yes this concerns immediate public safety",
        "Please",
        "Yes please",
        "Yes thank you",
        "Yes thanks",
        "Absolutely",
        "Please send this report",
        "Please send this report to Felidae Fund",
        "Pleaes send this report to Felidae",
        "Send this report",
        "Send this report to Felidae",
        "Send this report to Felida Fund",
        "Go ahead and send this report",
        "Please go ahead and send this report",
        "Yes please send my report",
        "Yes send my report",
        "Yes go ahead",
        "Yes please go ahead",
        "Yes please send to the team",
        "Yes let the team know",
        "Yes please let the team know",
        "Yes please inform the team"
    ]
}

module.exports = Affirmative;