const Negative = {
    name: "Negative",
    utterances: [
        "No",
        "Nope",
        "Nah",
        "Negative",
        "It did not",
        "No it is not",
        "No it isn't",
        "I don't think so",
        "I do not think so",
        "No there isn't",
        "No there is not",
        "There is not a public safety concern",
        "There isn't a public safety concern",
        "This is not a safetly concern",
        "This isn't a safetly concern",
        "This is not an immediate public safety concern",
        "This isn't an immediate public safety concern",
        "This is not an immediate safety concern",
        "This isn't an immediate safety concern",
        "There is not a concern for public safety",
        "There isn't a concern for public safety",
        "There is not an immediate concern for public safety",
        "There isn't an immediate concern for public safety",
        "This does not involve public safety",
        "This doesn't involve public safety",
        "This does not involve immediate public safety",
        "This doesn't involve immediate public safety",
        "This does not invole public safety",
        "This doesn't invole public safety",
        "This does not involve immediate public safety",
        "This doesn't involve immediate public safety",
        "This is not about public safety",
        "This isn't about public safety",
        "This is not about immediate public safety",
        "This isn't about immediate public safety",
        "This does not concern public safety",
        "This doesn't concern public safety",
        "This does not concern immediate public safety",
        "This doesn't concern immediate public safety",
        "This is not a public safety concern",
        "This isn't a public safety concern",
        "No I am not reporting a public safety concern",
        "No this does not affects public safety",
        "No this doesn't affects public safety",
        "No this does not invole public safety",
        "No this doesn't invole public safety",
        "No this does not concern public safety",
        "No this doesn't concern public safety",
        "No this does not concern immediate public safety",
        "No this doesn't concern immediate public safety",
        "No this is not about public safety",
        "No this isn't about public safety",
        "No this is not about immediate public safety",
        "No this isn't about immediate public safety",
        "No thanks",
        "Please don't",
        "Absolutely not",
        "Please do not",
        "Please don't",
        "No thank you"
    ]
}

module.exports = Negative;