// Welcome Intent
var WelcomeAlt = {
    name: 'WelcomeAlt',
    utterances: [
        "I would like to report a puma sighting",
        "I would like to report a cougar sighting",
        "I would like to report a mountain lion sighting",
        "I would like to report a big cat sighting",
        "I would like to report a panther sighting",
        "I would like to report a sighting to Felidae Fund", 
        "I would like to report a sighting to Felidae Conservation Fund",
        "I want to report a puma sighting",
        "I want to report a cougar sighting",
        "I want to report a mountain lion sighting",
        "I want to report a big cat sighting",
        "I want to report a panther sighting",
        "I want to report a sighting to Felidae Fund",
        "I want to report a sighting to Felidae Conseravation Fund",
        "report a puma sighting",
        "report a cougar sighting",
        "report a mountain lion sighting",
        "report a big cat sighting",
        "report a big panther sighting",
        "report a sighting to Felidae Fund",
        "report a sighting to Felidae Conservation Fund",
        "I saw a puma",
        "I saw a cougar",
        "I saw a mountain lion",
        "I saw a big cat",
        "I saw a panther",
        "I just saw a puma",
        "I just saw a cougar",
        "I just saw a mountain lion",
        "I just saw a big cat",
        "I just saw a panther",
        "Oh my god I saw a puma",
        "Oh my god I saw a cougar",
        "Oh my god I saw a mountain lion",
        "Oh my god I saw a big cat",
        "Oh my god I saw a panther",
        "Oh my god I just saw a puma",
        "Oh my god I just saw a cougar",
        "Oh my god I just saw a mountain lion",
        "Oh my god I just saw a big cat",
        "Oh my god I just saw a panther",
        "I just saw a wild cat",
        "I saw a wild cat",
        "report a wild cat sighting",
        "I want to report a wild cat sighting",
        "I would like to report a wild cat sighting",
        "report a wild cat sighting"
    ]
}

module.exports = WelcomeAlt